project: 
  type: website

website:
  title: "BioSCape Workshop at BioSpace25"
  site-url: https://nasa-openscapes.github.io/2025-biospace
  repo-url: https://github.com/NASA-Openscapes/2025-biospace
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "NASA Openscapes (2025). BioSCape Workshop at BioSpace25"
 
  navbar: 
    background: primary
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/NASA-Openscapes/2025-biospace
  sidebar:
    - id: welcome
      title: "Menu"
      logo: https://raw.githubusercontent.com/NASA-Openscapes/2025-biospace/refs/heads/main/images/bioscape.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - section: "Welcome"
          contents:
            - index.md
            - tutorials/prerequisites.md 
        - section: "Mapping invasive species using AVIRIS-NG"
          contents: 
            - href: tutorials/avirisng/avng_invasive_esaworkshop_noS3.ipynb
              text: "Machine learning with AVIRIS-NG"
        - section: "LVIS/GEDI Data for Ecosystem Structure"
          contents: 
            - href: tutorials/lvis/lvis.ipynb
              text: "LVIS/GEDI Data"

            
          
format:
  html:
    theme:
      light: sandstone
      dark: [sandstone, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
